# Code generated by ChatGPT

# python

import matplotlib.pyplot as plt
import pandas as pd

# Sample code to visualize alignment scores
alignment_data = pd.read_csv("alignment_stats.txt", sep="\t")
plt.plot(alignment_data["Position"], alignment_data["QualityScore"])
plt.title("Alignment Quality Scores")
plt.xlabel("Position")
plt.ylabel("Quality Score")
plt.show()
