# Code generated by ChatGPT

# bash

samtools view -bS aligned_reads.sam > aligned_reads.bam
samtools sort aligned_reads.bam -o sorted_reads.bam
samtools flagstat sorted_reads.bam > alignment_stats.txt
